// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarrailAssist.Data;

#nullable disable

namespace StarrailAssist.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarrailAssist.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("StarrailAssist.Models.Entities.AccountCharacter", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("AccountCharacters");
                });

            modelBuilder.Entity("StarrailAssist.Models.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LCEight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCFive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCFour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCNine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCSeven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCSix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCThree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCTwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StarrailAssist.Models.Entities.LightCone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LightCones");
                });

            modelBuilder.Entity("StarrailAssist.Models.Entities.AccountCharacter", b =>
                {
                    b.HasOne("StarrailAssist.Models.Entities.Account", "Account")
                        .WithMany("AccountCharacters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarrailAssist.Models.Entities.Character", "Character")
                        .WithMany("AccountCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("StarrailAssist.Models.Entities.Account", b =>
                {
                    b.Navigation("AccountCharacters");
                });

            modelBuilder.Entity("StarrailAssist.Models.Entities.Character", b =>
                {
                    b.Navigation("AccountCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
